version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file: 
      - .env # Mapeia o arquivo .env para o contêiner
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432

  postgres:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: quickpicsauth
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
